backend:
  name: github
  repo: lucasfads/lucasfads.github.io # Path to your GitHub repository

media_folder: "assets/images"

collections:
  - name: "website-settings"
    label: "Website settings"
    files:
      - label: "Website settings"
        name: "site"
        file: "_data/site.yml"
        fields:
          - label: "Year"
            name: "year"
            widget: "date"
            format: "YYYY"