backend:
  name: github
  repo: lucasfads/lucasfads.github.io # Path to your GitHub repository

media_folder: "assets/images"

collections:
  - name: "website-settings"
    label: "Website settings"
    files:
      - label: "Website settings"
        name: "site"
        file: "_data/site.yml"
        fields:
          - label: "Year"
            name: "year"
            widget: "string"

  - name: "portfolio"
    label: "Portfolio"
    folder: "_portfolio"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Categories"
        name: "categories"
        widget: "select"
        multiple: true
        options: ["Design de logotipo", "Web design", "Desenvolvimento"]
      - label: "Thumbnail image"
        name: "thumb"
        hint: "400*300px"
        widget: "image"
      - label: "Featured image"
        name: "featured"
        hint: "800*600px"
        widget: "image"
      - label: "Backgound color"
        name: "color"
        widget: "string"
      - label: "External URL to live web site"
        name: "live-site"
        widget: "string"
      - label: "Body"
        name: "body"
        widget: "markdown"